name: weekly-pull-request

on:
  push:
    branches:
      - weekly-learning-outcomes  # 監視したいブランチ名に変更

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      FILE_DIFF_SIZE: 3  # 差分ファイル数の閾値
    steps:
      - uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: sudo apt-get install gh

      - name: Count changed files not in main
        id: count
        run: |
          git fetch origin main
          FILE_COUNT=$(git diff --name-only origin/main..HEAD | wc -l)
          echo "count=$FILE_COUNT" >> $GITHUB_OUTPUT

      - name: Check for existing PR
        id: pr
        run: |
          gh pr list --base main --head ${{ github.ref_name }} --json number --jq '.[0].number' > pr_number.txt
          PR_NUMBER=$(cat pr_number.txt | tr -d '\n')
          if [ -n "$PR_NUMBER" ]; then
            echo "pr_exists=true" | tee -a $GITHUB_OUTPUT
            echo "pr_number=$PR_NUMBER" | tee -a $GITHUB_OUTPUT
          else
            echo "pr_exists=false" | tee -a $GITHUB_OUTPUT
            echo "pr_number=" | tee -a $GITHUB_OUTPUT
          fi
          # 出力値をログにも明示
          echo "[LOG] pr_exists=$(if [ -n \"$PR_NUMBER\" ]; then echo true; else echo false; fi)"
          echo "[LOG] pr_number=$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR body and title if PR already exists and threshold met
        if: steps.count.outputs.count >= env.FILE_DIFF_SIZE && steps.pr.outputs.pr_exists == 'true' && steps.pr.outputs.pr_number != ''
        run: |
          PR_NUMBER="${{ steps.pr.outputs.pr_number }}"
          git fetch origin main --unshallow || git fetch origin main
          TODAY=$(date +'%Y-%m-%d')
          DOW=$(date -d "$TODAY" +%w)
          DAYS_TO_SAT=$((6 - DOW))
          SATURDAY=$(date -d "$TODAY +$DAYS_TO_SAT day" +'%Y/%m/%d')
          COMMITS=$(git log origin/main..HEAD --pretty=format:'- [%h](https://github.com/${{ github.repository }}/commit/%H) %s (%an)' --reverse)
          BODY="## Commit Logs:\n\n$COMMITS"
          echo -e "$BODY" > body.txt
          gh pr edit $PR_NUMBER --title "$SATURDAY: Weekly Outcomes" --body-file body.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR if threshold met and no PR exists
        if: steps.count.outputs.count >= env.FILE_DIFF_SIZE && steps.pr.outputs.pr_exists == 'false'
        run: |
          git fetch origin main --unshallow || git fetch origin main
          TODAY=$(date +'%Y-%m-%d')
          DOW=$(date -d "$TODAY" +%w)
          DAYS_TO_SAT=$((6 - DOW))
          SATURDAY=$(date -d "$TODAY +$DAYS_TO_SAT day" +'%Y/%m/%d')
          COMMITS=$(git log origin/main..HEAD --pretty=format:'- [%h](https://github.com/${{ github.repository }}/commit/%H) %s (%an)' --reverse)
          BODY="## Commit Logs\n\n$COMMITS"
          echo -e "$BODY" > body.txt
          gh pr create --base main --head ${{ github.ref_name }} --title "$SATURDAY: Weekly Outcomes" --body-file body.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
